{["src/behaviours/*", "src/*", "src/parser/*", "src/monitor/*",
	"src/conversation/*", "src/util/*",
	"examples/TwoBuyer/*",
	"examples/Warehouse/*",
	"examples/*",
	"tests/monitor/*", "tests/util/*", "tests/behaviour/*"],
					[debug_info,
           {i, "src"},
           {i, "include"},
           {outdir, "ebin"}]}.
